"""Presets the planner composes from, and the safe zones the verifier measures
against (spec §2.8).

Four preset families live under `config.PRESETS_DIR`; three are JSON the repo
ships and one is generated:

  text_styles/*.json   named looks for `add_text` — role, font, size, anim,
                       and an ANCHOR name instead of a y fraction, so the
                       fraction always comes from SAFE_ZONES for the canvas
                       the text lands on (a 9:16 caption sits at 0.76, a
                       16:9 one at 0.85; a hard-coded number would be wrong
                       on one of them).
  transitions/*.json   named looks for `add_transition` — a cycle of types
                       and one duration; every type is validated against
                       `render.transitions.all_names()` at load, so a typo
                       fails here and never reaches a plan.
  (no catalog file)    the CapCut-style product surface — display name,
                       family, default duration and one line per distinct
                       look — is `render.transitions.entries()`;
                       `transition_catalog()` is a typed view over it. A
                       second hand-written copy used to live here and
                       disagreed with the renderer on 45 of 72 rows.
  templates/*.json     named whole-edit recipes (`auto_edit` variants) —
                       ordered `{recipe, slots}` entries plus the keywords the
                       grammar matches. Stage order comes from the recipe
                       table, never from the file.
  music/*.wav + .json  procedural beds, GENERATED by `generate_music_beds`
                       (CLI: scripts/gen_music_beds.py) and gitignored. The
                       sidecar carries the exact kick grid (`bpm`,
                       `beat_grid_offset`), so the beat_sync recipe needs no
                       beat detector for a preset bed.

WHY `SAFE_ZONES` lives here and is imported by the verifier AND the §4.9
handler defaults: TikTok/Reels chrome covers the bottom ~20% and the right
rail of a 9:16 frame, and the renderer anchored captions at
`canvas_h − 0.16·h` = 0.84 — inside the covered band. Rather than loosen the
check, the product defaults move up on vertical canvases; both sides read
the same table so they cannot disagree about where "safe" is.

WHY the loaders never raise on a missing directory: the packaged app ships
`presets/` via `--add-data`, but the music beds are generated at build time
and a source checkout that skipped the script has none. `music_beds()`
returns `[]` and the `music` recipe asks for an upload instead — degrade
honestly rather than 500 on "add music".
"""
from __future__ import annotations

import json
import math
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

from ... import config
from ... import platformutil as _pu

Aspect = Literal["9:16", "16:9", "1:1", "4:5", "other"]


# --------------------------------------------------------------------------
# 1. Safe zones
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class SafeZone:
    """Fractions of the canvas. Text anchors (block centres) must satisfy
    `y_min ≤ y ≤ y_max` and `x ≤ x_max`; `caption_y` / `lower_third_y` are the
    product defaults the §4.9 handlers place captions and lower thirds at."""
    y_min: float
    y_max: float
    x_max: float
    caption_y: float
    lower_third_y: float

    def contains(self, x_frac: float, y_frac: float) -> bool:
        return self.y_min <= y_frac <= self.y_max and x_frac <= self.x_max


SAFE_ZONES: dict[str, SafeZone] = {
    # TikTok/Reels/Shorts UI: caption/handle/actions cover the bottom ~20 %
    # and the like/comment rail the right ~15 %.
    "9:16": SafeZone(y_min=0.10, y_max=0.78, x_max=0.85, caption_y=0.76, lower_third_y=0.74),
    "1:1": SafeZone(y_min=0.08, y_max=0.90, x_max=1.0, caption_y=0.85, lower_third_y=0.80),
    "4:5": SafeZone(y_min=0.08, y_max=0.90, x_max=1.0, caption_y=0.85, lower_third_y=0.80),
    "16:9": SafeZone(y_min=0.05, y_max=0.92, x_max=1.0, caption_y=0.85, lower_third_y=0.80),
}

#: Roles that live in the margin by design and are exempt from the zone.
SAFE_ZONE_EXEMPT_ROLES: frozenset[str] = frozenset({"watermark"})

#: Canvas dimensions per aspect (mirrors dispatch.auto_reframe's table).
ASPECT_DIMS: dict[str, tuple[int, int]] = {
    "9:16": (1080, 1920), "16:9": (1920, 1080), "1:1": (1080, 1080), "4:5": (1080, 1350),
}


def aspect_of(w: int | float, h: int | float, *, tol: float = 0.02) -> Aspect:
    """Classify a w×h into the four named aspects, or "other". 2 % tolerance
    so 1080×1350 (0.8) and 1088×1360 both read as 4:5."""
    if not w or not h:
        return "other"
    r = float(w) / float(h)
    for name, (aw, ah) in ASPECT_DIMS.items():
        if abs(r - aw / ah) <= tol * (aw / ah):
            return name  # type: ignore[return-value]
    return "other"


def safe_zone_for(aspect: str) -> SafeZone:
    """The zone for an aspect; unknown/"other" canvases use the 16:9 zone,
    the most permissive one, because no platform chrome is known for them."""
    return SAFE_ZONES.get(aspect, SAFE_ZONES["16:9"])


# --------------------------------------------------------------------------
# 2. Paths
# --------------------------------------------------------------------------

def presets_dir() -> Path:
    """Read on every call so tests (and `desktop.py` under a custom WORKDIR)
    can monkeypatch `config.PRESETS_DIR` after import."""
    return Path(config.PRESETS_DIR)


def music_dir() -> Path:
    return presets_dir() / "music"


def _read_json_files(sub: str) -> dict[str, dict[str, Any]]:
    d = presets_dir() / sub
    if not d.is_dir():
        return {}
    out: dict[str, dict[str, Any]] = {}
    for p in sorted(d.glob("*.json")):
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, ValueError) as e:
            raise ValueError(f"preset {p} is not valid JSON: {e}") from e
        if not isinstance(data, dict):
            raise ValueError(f"preset {p} must be a JSON object")
        out[p.stem] = data
    return out


# --------------------------------------------------------------------------
# 3. Fonts / LUTs / templates the validator whitelists against
# --------------------------------------------------------------------------

def font_names() -> frozenset[str]:
    """Basenames AND stems of `fonts/*.ttf` — `add_text.font` is written as a
    stem ("Inter-Black") by every existing caller and `_font_path` joins it
    to FONTS_DIR verbatim, so both spellings are the same bundled file."""
    d = Path(config.FONTS_DIR)
    if not d.is_dir():
        return frozenset()
    names: set[str] = set()
    for p in d.glob("*.ttf"):
        names.add(p.name)
        names.add(p.stem)
    return frozenset(names)


def lut_names() -> frozenset[str]:
    """Bare `.cube` basenames in presets/luts — the only form a plan may pass
    to `apply_lut` (§1.3 rule 6)."""
    d = presets_dir() / "luts"
    if not d.is_dir():
        return frozenset()
    return frozenset(p.name for p in d.glob("*.cube"))


def show_template_names() -> frozenset[str]:
    d = presets_dir() / "shows"
    if not d.is_dir():
        return frozenset()
    return frozenset(p.stem for p in d.glob("*.json"))


# --------------------------------------------------------------------------
# 4. Text styles
# --------------------------------------------------------------------------

TextAnchor = Literal["caption", "lower_third", "hook", "top", "center", "upper_third"]
TEXT_ANCHORS: tuple[str, ...] = ("caption", "lower_third", "hook", "top", "center", "upper_third")


@dataclass(frozen=True)
class TextStylePreset:
    name: str
    role: str
    font: str
    anchor: str
    size: float | None = None
    color: str | None = None
    stroke: str | None = None
    stroke_w: float | None = None
    upper: bool | None = None
    anim_in: str | None = None
    anim_out: str | None = None
    description: str = ""

    def y_frac(self, aspect: str) -> float:
        """Anchor → fraction for THIS canvas, from SAFE_ZONES."""
        z = safe_zone_for(aspect)
        return {
            "caption": z.caption_y,
            "lower_third": z.lower_third_y,
            "hook": 0.5,
            "center": 0.5,
            "top": z.y_min + 0.05,
            "upper_third": max(z.y_min, 0.30),
        }[self.anchor]

    def add_text_args(self, *, text: str, start: float, end: float,
                      canvas_w: int, canvas_h: int, aspect: str) -> dict[str, Any]:
        """Exact `add_text` args for this look on a canvas. Only advertised
        keys, so the result passes `validate_plan` unchanged."""
        args: dict[str, Any] = {
            "text": text, "start": start, "end": end, "role": self.role,
            "font": self.font, "x": canvas_w / 2, "y": round(canvas_h * self.y_frac(aspect), 1),
        }
        for key in ("size", "color", "stroke", "stroke_w", "upper", "anim_in", "anim_out"):
            v = getattr(self, key)
            if v is not None:
                args[key] = v
        return args


_TEXT_ROLES = ("super", "hook", "lower_third", "caption", "label", "watermark", "default")
_ANIMS = ("pop", "fade", "slide_up", "slide_down")


def text_styles() -> dict[str, TextStylePreset]:
    """Every `presets/text_styles/*.json`, validated: role, anchor, anim names
    and the font (must be a bundled file — a preset naming a font that is not
    shipped would render in Inter-Bold silently, see `text_overlay._font_path`)."""
    fonts = font_names()
    out: dict[str, TextStylePreset] = {}
    for stem, data in _read_json_files("text_styles").items():
        role = str(data.get("role", "default"))
        if role not in _TEXT_ROLES:
            raise ValueError(f"text style {stem}: role {role!r} not in {_TEXT_ROLES}")
        anchor = str(data.get("anchor", "center"))
        if anchor not in TEXT_ANCHORS:
            raise ValueError(f"text style {stem}: anchor {anchor!r} not in {TEXT_ANCHORS}")
        font = str(data.get("font", "Inter-Bold.ttf"))
        if fonts and font not in fonts:
            raise ValueError(f"text style {stem}: font {font!r} is not a bundled font")
        for key in ("anim_in", "anim_out"):
            if data.get(key) is not None and data[key] not in _ANIMS:
                raise ValueError(f"text style {stem}: {key} {data[key]!r} not in {_ANIMS}")
        out[stem] = TextStylePreset(
            name=stem, role=role, font=font, anchor=anchor,
            size=float(data["size"]) if data.get("size") is not None else None,
            color=data.get("color"), stroke=data.get("stroke"),
            stroke_w=float(data["stroke_w"]) if data.get("stroke_w") is not None else None,
            upper=data.get("upper"), anim_in=data.get("anim_in"), anim_out=data.get("anim_out"),
            description=str(data.get("description", "")),
        )
    return out


# --------------------------------------------------------------------------
# 5. Transition looks
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class TransitionLook:
    name: str
    types: tuple[str, ...]
    duration: float
    description: str = ""

    def type_at(self, i: int) -> str:
        return self.types[i % len(self.types)]


#: A stale `presets/transitions/<this>.json` from 0.7.0-pre is skipped by the
#: look loader; the catalog itself is `render.transitions.entries()` now.
TRANSITION_CATALOG_STEM = "catalog"


def transition_looks() -> dict[str, TransitionLook]:
    from ...render.transitions import all_names
    valid = set(all_names())
    out: dict[str, TransitionLook] = {}
    for stem, data in _read_json_files("transitions").items():
        if stem == TRANSITION_CATALOG_STEM:
            continue
        types = tuple(str(t) for t in (data.get("types") or []))
        if not types:
            raise ValueError(f"transition look {stem}: no types")
        bad = [t for t in types if t not in valid]
        if bad:
            raise ValueError(f"transition look {stem}: unknown transition types {bad}")
        duration = float(data.get("duration", 0.4))
        if not 0.1 <= duration <= 2.0:
            raise ValueError(f"transition look {stem}: duration {duration} outside [0.1, 2]")
        out[stem] = TransitionLook(name=stem, types=types, duration=duration,
                                   description=str(data.get("description", "")))
    return out


#: Category ids and labels, in the order the Transitions panel shows them.
#: Ids are stable (the JSON, the UI tabs and the benchmark name them);
#: labels are what a user reads.
TRANSITION_CATEGORIES: tuple[tuple[str, str], ...] = (
    ("basic", "Basic"), ("light", "Light"), ("wipe", "Wipe"), ("slide", "Slide"),
    ("zoom", "Zoom"), ("blur", "Blur"), ("shape", "Shape"), ("stylised", "Glitch & Stylised"),
)
TRANSITION_CATEGORY_IDS: tuple[str, ...] = tuple(i for i, _ in TRANSITION_CATEGORIES)
TRANSITION_DURATION_RANGE = (0.1, 2.0)
DEFAULT_TRANSITION_DURATION = 0.5


@dataclass(frozen=True)
class TransitionEntry:
    """One renderable look as the product shows it."""
    name: str            # the canonical render/transitions name
    label: str           # "Fade to Black"
    category: str        # one of TRANSITION_CATEGORY_IDS
    duration: float      # default seconds
    description: str = ""

    def as_dict(self) -> dict[str, Any]:
        return {"name": self.name, "label": self.label, "category": self.category,
                "duration": self.duration, "description": self.description}


#: Product family (render.transitions.FAMILY_NAMES) → the stable category id
#: the panel tabs, the benchmark and the recipe cards use.
_FAMILY_TO_CATEGORY: dict[str, str] = {
    "Basic": "basic", "Light": "light", "Wipe": "wipe", "Slide": "slide", "Zoom": "zoom",
    "Blur": "blur", "Shape": "shape", "Glitch/Stylised": "stylised",
}


def transition_catalog() -> dict[str, TransitionEntry]:
    """Every distinct look `render/transitions.py` can render, as the product
    shows it — a thin view over `render.transitions.entries()`: label =
    `display_name`, category = the look's family, duration =
    `default_duration`, description = `DESCRIPTIONS`.

    ONE source on purpose. A second catalog (presets/transitions/catalog.json)
    used to carry its own labels, families and durations and disagreed with
    the renderer on 45 of 72 rows, so a tile click and the same tile's
    "Every cut · via Prompt" applied different durations, the run log named
    "Push Left" for a "Slide Left" click, and 19 display names resolved to the
    wrong look through the grammar. Raises when the renderer's table is
    inconsistent (a look without a family or description) — never a silent
    `{}` that reads as "no transitions installed"."""
    from ...render.transitions import CUSTOM_EXPRS, NATIVE, entries
    looks = set(NATIVE) | set(CUSTOM_EXPRS)
    out: dict[str, TransitionEntry] = {}
    lo, hi = TRANSITION_DURATION_RANGE
    for e in entries():
        name = str(e["name"])
        category = _FAMILY_TO_CATEGORY.get(str(e["family"]), "")
        if category not in TRANSITION_CATEGORY_IDS:
            raise ValueError(f"transition catalog: {name} family {e['family']!r} has no category id")
        label = str(e["display"]).strip()
        if not label:
            raise ValueError(f"transition catalog: {name} has no display name")
        duration = float(e["default_duration"])
        if not lo <= duration <= hi:
            raise ValueError(f"transition catalog: {name} duration {duration} outside {TRANSITION_DURATION_RANGE}")
        description = str(e.get("description") or "").strip()
        if not description:
            raise ValueError(f"transition catalog: {name} has no description (render.transitions.DESCRIPTIONS)")
        out[name] = TransitionEntry(name=name, label=label, category=category, duration=duration,
                                    description=description)
    missing = sorted(looks - set(out))
    if missing:
        raise ValueError(f"transition catalog has no entry for renderable looks: {missing}")
    return out


def transition_entry(name: str) -> TransitionEntry | None:
    """The catalog entry for ANY accepted name — aliases (`zoom`, `whippan`,
    `crossdissolve`) resolve to their canonical look. None for unknown."""
    from ...render.transitions import canonical, is_valid
    if not is_valid(name):
        return None
    return transition_catalog().get(canonical(name))


def transition_default_duration(name: str, fallback: float = DEFAULT_TRANSITION_DURATION) -> float:
    """Per-transition default seconds (a whip is 0.25, a fade to black 0.6).
    The compositor and the Transitions panel read this; `fallback` for a
    name outside the catalog."""
    entry = transition_entry(name)
    return entry.duration if entry is not None else fallback


def transitions_by_category() -> dict[str, list[TransitionEntry]]:
    """Category id → entries, categories in panel order, entries by label."""
    cat = transition_catalog()
    out: dict[str, list[TransitionEntry]] = {cid: [] for cid in TRANSITION_CATEGORY_IDS}
    for entry in sorted(cat.values(), key=lambda e: e.label):
        out[entry.category].append(entry)
    return out


# --------------------------------------------------------------------------
# 6. Edit templates (auto_edit variants)
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class EditTemplate:
    name: str
    description: str
    platform: str | None
    recipes: tuple[tuple[str, dict[str, Any]], ...]   # ordered (recipe, slots)
    keywords: tuple[str, ...] = ()
    exclusions: tuple[str, ...] = ()


def edit_templates() -> dict[str, EditTemplate]:
    """`presets/templates/*.json`. Recipe names are validated against the
    recipe table lazily (recipes.py imports this module, so the check imports
    it the other way only inside the function)."""
    from .recipes import RECIPE_SLOTS
    out: dict[str, EditTemplate] = {}
    for stem, data in _read_json_files("templates").items():
        entries: list[tuple[str, dict[str, Any]]] = []
        for item in data.get("recipes") or []:
            if isinstance(item, str):
                name, slots = item, {}
            else:
                name, slots = str(item.get("recipe")), dict(item.get("slots") or {})
            if name not in RECIPE_SLOTS:
                raise ValueError(f"template {stem}: unknown recipe {name!r}")
            unknown = set(slots) - set(RECIPE_SLOTS[name])
            if unknown:
                raise ValueError(f"template {stem}: recipe {name} has unknown slots {sorted(unknown)}")
            entries.append((name, slots))
        if not entries:
            raise ValueError(f"template {stem}: no recipes")
        out[stem] = EditTemplate(
            name=stem, description=str(data.get("description", "")),
            platform=data.get("platform"), recipes=tuple(entries),
            keywords=tuple(str(k).lower() for k in (data.get("keywords") or [])),
            exclusions=tuple(str(k) for k in (data.get("exclusions") or [])),
        )
    return out


# --------------------------------------------------------------------------
# 7. Music beds (generated)
# --------------------------------------------------------------------------

BED_DURATION_S = 180.0
BED_SAMPLE_RATE = 48000
BED_TARGET_LUFS = -18.0

#: (name, bpm, mood). Names are stable: the `music` recipe, K's benchmark
#: fixture and the .gitignore pattern all refer to them.
BED_SPECS: tuple[tuple[str, int, str], ...] = (
    ("chill_90bpm", 90, "chill"),
    ("upbeat_120bpm", 120, "upbeat"),
    ("cinematic_70bpm", 70, "cinematic"),
    ("lofi_85bpm", 85, "lofi"),
)
MOODS: tuple[str, ...] = tuple(m for _, _, m in BED_SPECS)


@dataclass(frozen=True)
class MusicBed:
    name: str
    path: Path
    bpm: float
    mood: str
    beat_grid_offset: float = 0.0
    duration_s: float = BED_DURATION_S
    source: str = "procedural"

    @property
    def period(self) -> float:
        return 60.0 / self.bpm

    def beats(self, until: float) -> list[float]:
        """Exact beat instants from the grid, in bed-local seconds, < `until`."""
        n = int(math.floor((until - self.beat_grid_offset) / self.period)) + 1
        return [round(self.beat_grid_offset + i * self.period, 6) for i in range(max(0, n))
                if self.beat_grid_offset + i * self.period < until]


def music_beds(directory: Path | None = None) -> list[MusicBed]:
    """Beds whose .wav AND .json sidecar exist; `[]` when none were generated.
    Never raises for a missing directory (see module docstring)."""
    d = Path(directory) if directory is not None else music_dir()
    if not d.is_dir():
        return []
    out: list[MusicBed] = []
    for sidecar in sorted(d.glob("*.json")):
        wav = sidecar.with_suffix(".wav")
        if not wav.exists():
            continue
        try:
            meta = json.loads(sidecar.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        try:
            out.append(MusicBed(
                name=sidecar.stem, path=wav.resolve(), bpm=float(meta["bpm"]),
                mood=str(meta.get("mood", sidecar.stem.split("_")[0])),
                beat_grid_offset=float(meta.get("beat_grid_offset", 0.0)),
                duration_s=float(meta.get("duration_s", BED_DURATION_S)),
                source=str(meta.get("source", "procedural")),
            ))
        except (KeyError, TypeError, ValueError):
            continue
    return out


def bed_for_mood(mood: str | None, directory: Path | None = None) -> MusicBed | None:
    beds = music_beds(directory)
    if not beds:
        return None
    if mood:
        for b in beds:
            if b.mood == mood:
                return b
    return next((b for b in beds if b.mood == "chill"), beds[0])


def _bed_expression(bpm: int, mood: str) -> str:
    """A deterministic lavfi `aevalsrc` expression: a kick exactly on the beat
    grid (t = k·60/bpm), a lighter click on the off-beats, and a slow pad.
    Written so librosa's beat tracker and the sidecar grid agree: the kick is
    the loudest transient by a wide margin and nothing else is periodic at a
    competing rate."""
    p = 60.0 / bpm
    ph = f"(t-floor(t/{p:.6f})*{p:.6f})"          # seconds since the last beat
    half = f"(t+{p / 2:.6f}-floor((t+{p / 2:.6f})/{p:.6f})*{p:.6f})"  # since the last off-beat
    # The beat carries BOTH the kick and the sharpest transient. A first
    # version put the only click on the off-beats and librosa locked onto it
    # (detected beats sat at 0.766, 1.277 … on a 120 BPM grid: the off-beats),
    # which would have made every "split lands on a detected beat" check
    # disagree with the sidecar grid by half a period.
    kick = f"0.9*sin(2*PI*(52+40*exp(-{ph}*30))*{ph})*exp(-{ph}*11)"
    snap = f"0.4*sin(2*PI*2600*t)*exp(-{ph}*120)"
    click = f"0.08*sin(2*PI*3200*t)*exp(-{half}*90)"
    pads = {
        "chill": "0.06*(sin(2*PI*220*t)+sin(2*PI*277.18*t)+sin(2*PI*329.63*t))*(0.6+0.4*sin(2*PI*0.08*t))",
        "upbeat": "0.06*(sin(2*PI*261.63*t)+sin(2*PI*329.63*t)+sin(2*PI*392*t))*(0.7+0.3*sin(2*PI*0.25*t))",
        "cinematic": "0.07*(sin(2*PI*110*t)+sin(2*PI*164.81*t)+sin(2*PI*196*t))*(0.5+0.5*sin(2*PI*0.05*t))",
        "lofi": "0.05*(sin(2*PI*196*t)+sin(2*PI*246.94*t)+sin(2*PI*293.66*t))*(0.6+0.4*sin(2*PI*0.12*t))",
    }[mood]
    return f"{kick}+{snap}+{click}+{pads}"


_LUFS_RE = re.compile(r"I:\s*(-?[\d.]+)\s*LUFS")


def _measure_lufs(path: Path) -> float:
    proc = subprocess.run(
        [_pu.FFMPEG, "-hide_banner", "-nostats", "-i", str(path),
         "-af", "ebur128=peak=none", "-f", "null", "-"],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        **_pu.SUBPROCESS_FLAGS)
    hits = _LUFS_RE.findall(proc.stderr)
    if not hits:
        raise RuntimeError(f"ebur128 gave no integrated loudness for {path}: {proc.stderr[-400:]}")
    return float(hits[-1])


def _run_ffmpeg(args: list[str]) -> None:
    proc = subprocess.run([_pu.FFMPEG, "-y", "-hide_banner", "-loglevel", "error", *args],
                          capture_output=True, text=True, encoding="utf-8", errors="replace",
                          **_pu.SUBPROCESS_FLAGS)
    if proc.returncode != 0:
        raise RuntimeError(f"ffmpeg failed: {proc.stderr[-600:]}")


def generate_music_beds(out_dir: Path | None = None, *, duration_s: float = BED_DURATION_S,
                        force: bool = False) -> list[MusicBed]:
    """Write the four beds + sidecars into `out_dir` (default presets/music).

    Deterministic: lavfi synthesis, then a measured gain (ebur128 → `volume`)
    to land on −18 LUFS. Two passes rather than `loudnorm` because loudnorm's
    dynamic mode reshapes transients and would smear the kick grid the
    sidecar promises is exact. Existing files are kept unless `force`.
    """
    d = Path(out_dir) if out_dir is not None else music_dir()
    d.mkdir(parents=True, exist_ok=True)
    made: list[MusicBed] = []
    for name, bpm, mood in BED_SPECS:
        wav = d / f"{name}.wav"
        sidecar = d / f"{name}.json"
        if wav.exists() and sidecar.exists() and not force:
            made.extend(b for b in music_beds(d) if b.name == name)
            continue
        raw = d / f"{name}.raw.wav"
        expr = _bed_expression(bpm, mood)
        _run_ffmpeg(["-f", "lavfi", "-i", f"aevalsrc='{expr}':s={BED_SAMPLE_RATE}:d={duration_s:.3f}",
                     "-ac", "1", "-c:a", "pcm_s16le", str(raw)])
        gain = BED_TARGET_LUFS - _measure_lufs(raw)
        _run_ffmpeg(["-i", str(raw), "-af", f"volume={gain:.3f}dB",
                     "-ac", "2", "-ar", str(BED_SAMPLE_RATE), "-c:a", "pcm_s16le", str(wav)])
        raw.unlink(missing_ok=True)
        sidecar.write_text(json.dumps({
            "bpm": bpm, "mood": mood, "source": "procedural", "beat_grid_offset": 0.0,
            "duration_s": duration_s, "lufs": BED_TARGET_LUFS, "sample_rate": BED_SAMPLE_RATE,
        }, indent=2), encoding="utf-8")
        made.append(MusicBed(name=name, path=wav.resolve(), bpm=bpm, mood=mood,
                             duration_s=duration_s))
    return made


__all__ = [
    "Aspect", "SafeZone", "SAFE_ZONES", "SAFE_ZONE_EXEMPT_ROLES", "ASPECT_DIMS",
    "aspect_of", "safe_zone_for", "presets_dir", "music_dir",
    "font_names", "lut_names", "show_template_names",
    "TextStylePreset", "TEXT_ANCHORS", "text_styles",
    "TransitionLook", "transition_looks", "TRANSITION_CATALOG_STEM",
    "TRANSITION_CATEGORIES", "TRANSITION_CATEGORY_IDS", "TRANSITION_DURATION_RANGE",
    "DEFAULT_TRANSITION_DURATION", "TransitionEntry", "transition_catalog", "transition_entry",
    "transition_default_duration", "transitions_by_category",
    "EditTemplate", "edit_templates",
    "BED_DURATION_S", "BED_SAMPLE_RATE", "BED_TARGET_LUFS", "BED_SPECS", "MOODS",
    "MusicBed", "music_beds", "bed_for_mood", "generate_music_beds",
]
