"""Normalize uploads to constant-framerate, common codec, common sample rate.

Without this, frame-accurate cuts and concat filters break on variable-framerate
sources or mixed sample rates.

HDR (BT.2020 PQ/HLG) sources need tone-mapping to look right in SDR. We apply a
tone-map LUT generated by `ingest/hdr.py` through the built-in `lut3d` filter
(works on every ffmpeg build), then `zscale+tonemap` if this ffmpeg has libzimg,
and only as a last resort a plain decode — which is still RETAGGED BT.709 so
8-bit SDR pixels never carry SMPTE-2084 tags (QA-042). The old middle attempt,
`colorspace=all=bt709`, was removed: that filter rejects the smpte2084 transfer,
so it could never succeed on the one kind of source it was there for.
"""
from __future__ import annotations
import json
import subprocess
import threading
from pathlib import Path
from typing import Callable
from .probe import probe, ProbeResult
from .hdr import BT709_TAGS, HLG_TRANSFERS, PQ_TRANSFERS, tonemap_chain, write_tonemap_lut
from .. import platformutil as _pu


_HDR_TRANSFERS = {"smpte2084", "smpte428", "arib-std-b67"}


def _has_filter(name: str) -> bool:
    """Cheap check: is this filter available in the local ffmpeg build?"""
    try:
        out = subprocess.run([_pu.FFMPEG, "-hide_banner", "-filters"],
                             capture_output=True, text=True, encoding="utf-8", errors="replace", check=True, **_pu.SUBPROCESS_FLAGS)
        return any(line.split()[1:2] == [name] for line in out.stdout.splitlines())
    except Exception:
        return False


def _color_meta(src: Path) -> dict:
    try:
        out = subprocess.run(
            [_pu.FFPROBE, "-v", "error", "-select_streams", "v:0",
             "-show_entries", "stream=color_transfer,color_primaries,color_space,pix_fmt",
             "-of", "json", str(src)],
            capture_output=True, text=True, encoding="utf-8", errors="replace", check=True,
            **_pu.SUBPROCESS_FLAGS,
        )
        data = json.loads(out.stdout)
        return (data.get("streams") or [{}])[0]
    except Exception:
        return {}


def _is_hdr(meta: dict) -> bool:
    return (meta.get("color_transfer") or "").lower() in _HDR_TRANSFERS


def _vf_for_short_side(short_side: int | None) -> str:
    """Scale so the SHORT side of the DISPLAYED frame is `short_side`.

    QA-008: this used to be ``scale=-2:<height>``, i.e. it pinned the output
    HEIGHT, and the clamp tested ``height > 1080`` — the LONG side of a
    portrait frame. A 1080x1920 phone clip was therefore shrunk to 608x1080
    and every vertical export was upscaled back from it (SSIM 0.935 vs 0.987
    for the same content in landscape). Evaluated inside ffmpeg on ``iw``/``ih``
    — the frame AFTER autorotation — because a phone clip stored as 1920x1080
    with a 90° rotation tag is displayed portrait, and a decision made from the
    coded dimensions would squash exactly those files."""
    if short_side is None:
        return ""
    s = int(short_side)
    return f"scale=w='if(gte(iw,ih),-2,{s})':h='if(gte(iw,ih),{s},-2)'"


def _has_stream(src: Path, kind: str) -> bool:
    """True if `src` has at least one stream of `kind` ('a' or 'v')."""
    try:
        out = subprocess.run(
            [_pu.FFPROBE, "-v", "error", "-select_streams", kind,
             "-show_entries", "stream=index", "-of", "csv=p=0", str(src)],
            capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=20,
            **_pu.SUBPROCESS_FLAGS,
        )
        return bool(out.stdout.strip())
    except Exception:
        return True  # assume present; the render has its own fallbacks


def _has_audio(src: Path) -> bool:
    """True if `src` has at least one audio stream."""
    return _has_stream(src, "a")


def _has_video(src: Path) -> bool:
    """True if `src` has at least one video stream.

    The mirror of `_has_audio`. Without it, normalizing an audio-only file
    succeeded (ffmpeg happily writes an audio-only mp4 and exits 0), so the
    upload landed on v1 as a `.normalized.mp4` with no picture — and every
    later render died on `[i:v] … matches no streams`.
    """
    return _has_stream(src, "v")


def _attempts(src: Path, dst: Path, fps: str, sample_rate: int, channels: int,
              short_side: int | None, transfer: str | None,
              lut_path: Path | None) -> list[tuple[str, list[str]]]:
    """Ordered (label, ffmpeg args) attempts, simplest-likely-to-work last.

    `fps` is an ffmpeg rate string (``"25"``, ``"30000/1001"``) from
    `edl.timebase.ffmpeg_rate` — never a rounded decimal. The label says what
    the attempt did to colour ("tonemapped" / "approximate" / "sdr"), which
    `normalize` reports so the upload can tell the user an HDR clip was only
    converted approximately."""
    common_audio = ["-c:a", "aac", "-ar", str(sample_rate), "-ac", str(channels)]
    common_video = ["-c:v", "libx264", "-preset", "veryfast", "-crf", "20",
                    "-fps_mode", "cfr", "-r", fps]
    tail = ["-movflags", "+faststart", "-progress", "pipe:1", "-nostats", str(dst)]
    has_audio = _has_audio(src)
    hdr = transfer in _HDR_TRANSFERS

    def with_vf(vf: str, extra: list[str] | None = None) -> list[str]:
        # When the source has no audio (silent screen recordings, GIF-style
        # clips), inject a silent stereo track so EVERY normalized file has
        # audio. The renderer concats per-clip [i:a] streams; a missing audio
        # stream there fails the whole filtergraph ("':a' matches no streams").
        if has_audio:
            a = [_pu.FFMPEG, "-y", "-i", str(src), *common_video]
        else:
            a = [_pu.FFMPEG, "-y", "-i", str(src),
                 "-f", "lavfi", "-i",
                 f"anullsrc=channel_layout=stereo:sample_rate={sample_rate}",
                 "-map", "0:v:0", "-map", "1:a:0", "-shortest", *common_video]
        if vf:
            a += ["-vf", vf]
        else:
            a += ["-pix_fmt", "yuv420p"]
        return a + (extra or []) + common_audio + tail

    def join(*parts: str) -> str:
        return ",".join(p for p in parts if p)

    attempts: list[tuple[str, list[str]]] = []
    scale = _vf_for_short_side(short_side)

    if hdr:
        # Attempt 1: our own tone-map LUT through the built-in lut3d filter —
        # works on every ffmpeg build (QA-042; see ingest/hdr.py).
        if lut_path is not None:
            chain = tonemap_chain(_pu.ffmpeg_filter_path(lut_path))
            attempts.append(("tonemapped", with_vf(join(chain, scale), BT709_TAGS)))
        # Attempt 2: zscale+tonemap, when this ffmpeg has libzimg.
        if _has_filter("zscale"):
            chain = ("zscale=t=linear:npl=100,format=gbrpf32le,"
                     "tonemap=tonemap=hable:desat=0,"
                     "zscale=p=bt709:t=bt709:m=bt709:r=tv,format=yuv420p,"
                     "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709")
            attempts.append(("tonemapped", with_vf(join(chain, scale), BT709_TAGS)))
        # Attempt 3: no tone map at all, but NEVER leave HDR tags on 8-bit SDR
        # pixels — that is the half of QA-042 players trip over.
        retag = "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709"
        attempts.append(("approximate", with_vf(join(scale, "format=yuv420p", retag), BT709_TAGS)))
    else:
        # Plain SDR / pix_fmt yuv420p.
        attempts.append(("sdr", with_vf(scale)))

    # Last resort: video-only (drop audio entirely; some sources have weird
    # audio codecs we can't transcode).
    fallback = [_pu.FFMPEG, "-y", "-i", str(src), "-an", *common_video,
                "-pix_fmt", "yuv420p"]
    vf = join(scale, "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709" if hdr else "")
    if vf:
        fallback += ["-vf", vf]
    if hdr:
        fallback += BT709_TAGS
    fallback += tail
    attempts.append(("approximate" if hdr else "sdr", fallback))

    return attempts


class NormalizeCancelled(RuntimeError):
    """The caller's cancel_event fired while ffmpeg was running."""


def _run_with_progress(args: list[str], duration: float,
                       on_progress: Callable[[float], None] | None,
                       cancel_event: "threading.Event | None") -> tuple[int, str]:
    """Run ffmpeg, streaming `-progress pipe:1` into `on_progress(0..1)`.

    stderr goes to a temp file rather than a pipe so a chatty ffmpeg can never
    fill a pipe buffer and deadlock against our stdout reader."""
    import tempfile
    with tempfile.TemporaryFile(mode="w+b") as err:
        proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=err,
                                **_pu.SUBPROCESS_FLAGS)
        assert proc.stdout is not None
        try:
            for raw in proc.stdout:
                if cancel_event is not None and cancel_event.is_set():
                    proc.terminate()
                    proc.wait(timeout=10)
                    raise NormalizeCancelled("import cancelled")
                line = raw.decode("utf-8", "replace").strip()
                if on_progress is None or duration <= 0:
                    continue
                key, _, value = line.partition("=")
                if key in ("out_time_us", "out_time_ms"):   # both are µs in ffmpeg
                    try:
                        on_progress(max(0.0, min(1.0, int(value) / 1e6 / duration)))
                    except ValueError:
                        pass
            rc = proc.wait()
        finally:
            if proc.poll() is None:
                proc.kill()
                proc.wait()
        err.seek(0)
        return rc, err.read().decode("utf-8", "replace")


def normalize(src: Path, dst: Path, fps: float | int | str | None = None,
               sample_rate: int = 48000, channels: int = 2,
               height: int | None = None, *,
               on_progress: Callable[[float], None] | None = None,
               cancel_event: "threading.Event | None" = None,
               report: dict | None = None) -> ProbeResult:
    """Re-encode to CFR H.264 yuv420p + AAC stereo. Tries multiple strategies.

    `fps=None` normalises at the SOURCE's own rate (QA-009: this used to be a
    hardcoded 30, so 25 fps sources gained a duplicate every 5th frame and
    59.94 lost half its motion) — see `edl.timebase.source_rate`. `height` is
    the target SHORT side (QA-008), None keeps the source resolution.

    `report`, when given, is filled with ``fps`` (the ffmpeg rate used) and
    ``color`` ("sdr" | "tonemapped" | "approximate"); "approximate" means an
    HDR source could not be tone-mapped and was only retagged.
    """
    from ..edl import timebase as _tb
    dst.parent.mkdir(parents=True, exist_ok=True)
    meta = _color_meta(src)
    transfer = (meta.get("color_transfer") or "").lower() or None
    try:
        src_probe: ProbeResult | None = probe(src)
    except Exception:
        src_probe = None
    if fps is None:
        v = src_probe.video if src_probe else None
        rate = _tb.source_rate(v.avg_frame_rate if v else None, v.r_frame_rate if v else None)
    else:
        rate = _tb.rate_of(_tb._fraction_or_none(fps))
    fps_arg = _tb.ffmpeg_rate(rate)
    duration = float(src_probe.duration) if src_probe and src_probe.duration else 0.0
    last_err = ""
    # Stage every attempt and swap on success — the write-temp-then-replace
    # pattern used by thumbs.py, text_overlay.py and the compositor's .part.mp4.
    # This was the one writer that pointed ffmpeg at its FINAL path, so the
    # freshly-uploaded file existed at its serving path while still being written:
    # a /thumb or /preview arriving in that window read a torn mp4 and 422'd
    # (reported as "transient 422 right after upload, succeeds moments later").
    # Staging closes the window entirely rather than making it smaller.
    tmp = _pu.part_path(dst)
    lut_path: Path | None = None
    if transfer in PQ_TRANSFERS or transfer in HLG_TRANSFERS:
        lut_path = dst.with_name(f".{dst.stem}.tonemap.cube")
        try:
            write_tonemap_lut(transfer, lut_path)
        except Exception:
            lut_path = None
    try:
        for label, args in _attempts(src, tmp, fps_arg, sample_rate, channels,
                                     height, transfer, lut_path):
            rc, err = _run_with_progress(args, duration, on_progress, cancel_event)
            if rc == 0 and tmp.exists() and tmp.stat().st_size > 0:
                _pu.replace_with_retry(tmp, dst)
                if report is not None:
                    report.update({"fps": fps_arg, "color": label,
                                   "transfer": transfer})
                return probe(dst)
            last_err = err
            # A failed attempt can leave a partial file that would satisfy the
            # size check on the NEXT attempt's early exit — clear it between tries.
            _pu.unlink_with_retry(tmp)
    finally:
        _pu.unlink_with_retry(tmp)
        if lut_path is not None:
            _pu.unlink_with_retry(lut_path)

    msg = last_err[-1200:] if last_err else "(no attempts ran)"
    raise RuntimeError(
        f"Couldn't normalize this video. It may use a codec or container we don't "
        f"yet support. Try exporting as standard H.264 .mp4 and re-uploading.\n\n"
        f"ffmpeg said:\n{msg}"
    )


def make_proxy(src: Path, dst: Path, height: int = 540, fps: float | int | None = 30) -> ProbeResult:
    """Low-res proxy media for fast preview rendering on long-form sources."""
    return normalize(src, dst, fps=fps, sample_rate=48000, channels=2, height=height)
