import { useEffect, useMemo, useRef, useState } from 'react'
import { useStore } from '../store'
import { defaultOverlayEnd, videoContentEnd } from '../lib/timelineExtent'
import { api } from '../api'
import { codepointSeq } from '../lib/emojiArt'
import { EMOJI_CATALOG, EMOJI_COUNT, type EmojiEntry } from '../lib/emojiCatalog'
import { searchEmoji } from '../lib/emojiSearch'

// The picker offers the WHOLE renderable emoji set, generated by
// scripts/gen_emoji_catalog.py. It used to be 113 hand-picked "viral" emoji,
// which fails in the one way a picker must not: the emoji you want is simply
// absent, with nothing to tell you the app supports it perfectly well
// ("I couldn't find 😁"). A curated list also rots silently as Unicode grows.
//
// Three things make the full set usable rather than overwhelming, and they are
// the reason this is not just a longer array:
//   • SEARCH is the primary way in. 1906 swatches is not a list you scan.
//   • Groups render their swatches only while OPEN, so the DOM holds one
//     section's worth, not all of them.
//   • Skin tones are a per-panel CHOICE rather than 1875 extra grid entries
//     (half the RGI set is tone variants — inlining them buries every base
//     emoji among five near-identical neighbours).
const RECENT_KEY = 'vai_recent_emojis'
const MAX_RECENT = 16
const TONE_KEY = 'vai_emoji_tone'
/** Index into EmojiEntry.t, or -1 for the default yellow. */
const TONE_SWATCHES = ['✋', '✋🏻', '✋🏼', '✋🏽', '✋🏾', '✋🏿']

/** Most emoji warmed in one request. A grid row is 8 swatches and the panel
 *  shows ~12 rows, so this is several screens' worth — enough that scrolling
 *  stays instant, bounded enough that opening the picker is not a download. */
const PREWARM_MAX = 128
const PREWARM_DEBOUNCE_MS = 300
/** Warmed this page-load, so re-opening the picker or re-expanding a group
 *  costs nothing. Module-level: the panel unmounts with the Media/AI tab. */
const PREWARMED = new Set<string>()

/** Apply the panel's skin tone to `e`, when it has one. */
function toned(e: EmojiEntry, tone: number): string {
  return tone >= 0 && e.t ? e.t[tone] : e.c
}

function loadTone(): number {
  const v = Number(localStorage.getItem(TONE_KEY))
  return Number.isInteger(v) && v >= -1 && v <= 4 ? v : -1
}

function loadRecent(): string[] {
  try {
    const v = localStorage.getItem(RECENT_KEY)
    return v ? JSON.parse(v) : []
  } catch {
    return []
  }
}

function pushRecent(e: string) {
  const cur = loadRecent().filter((x) => x !== e)
  cur.unshift(e)
  localStorage.setItem(RECENT_KEY, JSON.stringify(cur.slice(0, MAX_RECENT)))
}

export function StickerPanel() {
  const dispatch = useStore((s) => s.dispatch)
  const sid = useStore((s) => s.sessionId)
  const refresh = useStore((s) => s.refresh)
  const playhead = useStore((s) => s.playhead)
  const edl = useStore((s) => s.edl)
  const [recent, setRecent] = useState<string[]>(loadRecent())
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [tone, setTone] = useState<number>(loadTone())
  // Only the first group starts expanded. Opening one renders its swatches;
  // everything else stays out of the DOM until asked for.
  const [openGroups, setOpenGroups] = useState<Set<string>>(
    () => new Set([EMOJI_CATALOG[0]?.name].filter(Boolean) as string[]))
  const fileRef = useRef<HTMLInputElement>(null)
  const pickerRef = useRef<HTMLDivElement>(null)
  const [uploadErr, setUploadErr] = useState<string | null>(null)

  // DEBOUNCED, because the cost of a search is not the scan — it is painting an
  // <img> per result, each of which may start a fetch. Running that per
  // keystroke while someone types "rocket" does it six times and throws five
  // away, which is what "search is slow" actually was. The scan itself is ~1ms.
  const [debounced, setDebounced] = useState('')
  useEffect(() => {
    const t = setTimeout(() => setDebounced(query), 110)
    return () => clearTimeout(t)
  }, [query])

  // Ranked, not filtered — see lib/emojiSearch for why order is the whole
  // problem. The cap is applied after sorting, so it can never cost the best
  // answer the way a scan-and-stop cap did.
  const results = useMemo(
    () => (debounced.trim() ? searchEmoji(debounced, 96) : null),
    [debounced])

  // The emoji the picker is ABOUT TO DRAW — search results, or the recents plus
  // whichever groups are expanded. Not the catalogue.
  const visible = useMemo(() => {
    if (!open) return [] as string[]
    if (results) return results.map((e) => toned(e, tone))
    const out = [...recent]
    for (const g of EMOJI_CATALOG) {
      if (!openGroups.has(g.name)) continue
      for (const e of g.emojis) out.push(toned(e, tone))
    }
    return out
  }, [open, results, recent, openGroups, tone])

  // Warm the artwork cache for what is on screen, and only that.
  //
  // Warming exists for a real reason: a browser opens ~6 connections per origin,
  // so on a cold cache a group's swatches trickled in over many seconds, and
  // `serve_emoji_png` is a SYNC endpoint on the shared anyio threadpool. But the
  // first version asked for the WHOLE catalogue — every entry plus all five skin
  // tones, 3436 strings — the moment the picker opened. On a fresh install that
  // is ~3400 CDN requests fired by the act of clicking "Stickers", for artwork
  // of which the user will look at maybe two dozen. Nobody asked for that, most
  // of it is thrown away, and every one of those requests leaves this machine.
  //
  // Scoped to the visible set it is the same optimisation without the burst:
  // opening the panel warms the recents and the one expanded group (169 emoji
  // at most, capped at PREWARM_MAX), a search warms its own results, and
  // expanding another group warms that group when it is expanded. Everything
  // else is still fetched on demand by the `loading="lazy"` <img> below, exactly
  // as before — this only ever changes WHEN a fetch happens, never whether the
  // artwork is the fetched artwork, which is the invariant the whole emoji
  // subsystem rests on (never the OS font; see lib/emojiArt.ts).
  useEffect(() => {
    const fresh = visible.filter((e) => !PREWARMED.has(e)).slice(0, PREWARM_MAX)
    if (fresh.length === 0) return
    // Debounced for the same reason the search box is: typing "rocket", or
    // clicking through three groups, must not fire a request per keystroke.
    const t = setTimeout(() => {
      // Marked only once the request actually goes out — an effect torn down
      // before the timer fires has warmed nothing.
      for (const e of fresh) PREWARMED.add(e)
      void fetch('/api/emoji/prewarm', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ emojis: fresh }),
      }).catch(() => {})
    }, PREWARM_DEBOUNCE_MS)
    return () => clearTimeout(t)
  }, [visible])

  // Close the picker when clicking anywhere outside it. The ref wraps the
  // toggle button too, so clicking the toggle to close it doesn't fall through
  // here and immediately re-open.
  useEffect(() => {
    if (!open) return
    const onDown = (e: MouseEvent) => {
      if (pickerRef.current && !pickerRef.current.contains(e.target as Node)) {
        setOpen(false)
      }
    }
    document.addEventListener('mousedown', onDown)
    return () => document.removeEventListener('mousedown', onDown)
  }, [open])

  const insert = async (emoji: string) => {
    const w = edl?.canvas.w ?? 1080
    const h = edl?.canvas.h ?? 1920
    // The end of the PICTURE, not edl.duration. edl.duration is a max over
    // every track, so it already includes overlays — clamping to it is circular:
    // one overlay that overshoots the video licenses the next one to overshoot
    // just as far, and the timeline keeps growing a black tail.
    const duration = videoContentEnd(edl) || (playhead + 3.0)
    // Guarantee a real 3s window: if the playhead is close enough to the end
    // that a plain [playhead, playhead+3] clamped to duration would collapse
    // to near-zero, pull start back so the full 3s fits before the end
    // instead (never before 0). Inserting an emoji right at the tail of the
    // timeline used to silently produce a near-invisible sticker — issue 31b.
    const start = Math.max(0, Math.min(playhead, duration - 3.0))
    await dispatch('add_sticker', {
      emoji,
      start,
      end: defaultOverlayEnd(start, 3.0, videoContentEnd(edl)),
      position: [w / 2, h * 0.55],
    })
    pushRecent(emoji)
    setRecent(loadRecent())
  }

  return (
    <div ref={pickerRef} className="sticker-picker" style={{ marginTop: 16 }}>
      <button
        style={{ width: '100%', fontSize: 11 }}
        onClick={() => setOpen((o) => !o)}
        title="Emoji & sticker picker"
      >
        {/* The header icon is artwork too. It labels the emoji feature and sits
            directly above the grid, so an OS glyph here advertises one design
            for a picker that hands you another — the same promise the swatches
            broke, one line higher up. Plain typographic marks (▼ ▶ ✕ ✓) stay
            characters: they are not emoji and no artwork exists for them. */}
        {open ? '▼' : '▶'} <EmojiArt emoji="😀" size={13} inline /> Stickers
      </button>
      {open && (
        <div style={{ marginTop: 8 }}>
          <input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder={`Search ${EMOJI_COUNT} emoji…`}
            style={{ width: '100%', fontSize: 11, padding: '4px 6px', marginBottom: 6,
                     background: 'var(--bg-2)', border: '1px solid var(--line)',
                     borderRadius: 4, color: 'inherit' }}
          />
          {/* Skin tone is a panel-wide choice, not 1875 extra swatches. Only
              emoji that actually ship all five variants follow it; the rest
              ignore it, which is why the entry carries `t` rather than the UI
              trying to append a modifier and hoping artwork exists. */}
          <div style={{ display: 'flex', gap: 2, marginBottom: 6 }}>
            {TONE_SWATCHES.map((sw, i) => {
              const val = i - 1
              const on = tone === val
              return (
                <button
                  key={sw}
                  title={val < 0 ? 'Default' : `Skin tone ${val + 1}`}
                  onClick={() => { setTone(val); localStorage.setItem(TONE_KEY, String(val)) }}
                  style={{ flex: 1, padding: '2px 0', height: 22,
                           background: on ? 'var(--accent, #6c8cff)' : 'var(--bg-2)',
                           border: '1px solid var(--line)', borderRadius: 4,
                           cursor: 'pointer' }}
                >
                  <EmojiArt emoji={sw} size={14} />
                </button>
              )
            })}
          </div>
          {results ? (
            results.length ? (
              <EmojiRow label={`${results.length}${results.length === 96 ? '+' : ''} match${results.length === 1 ? '' : 'es'}`}
                        emojis={results.map((e) => toned(e, tone))} onPick={insert} />
            ) : (
              <div style={{ fontSize: 10, color: 'var(--text-dim)', padding: '6px 0' }}>
                No emoji match “{debounced}”.
              </div>
            )
          ) : (
            <>
              {recent.length > 0 && (
                <EmojiRow label="Recent" emojis={recent} onPick={insert} />
              )}
              {EMOJI_CATALOG.map((g) => {
                const isOpen = openGroups.has(g.name)
                return (
                  <div key={g.name}>
                    <button
                      onClick={() => setOpenGroups((prev) => {
                        const next = new Set(prev)
                        if (!next.delete(g.name)) next.add(g.name)
                        return next
                      })}
                      style={{ width: '100%', textAlign: 'left', fontSize: 10,
                               padding: '3px 0', background: 'none',
                               border: 'none', color: 'var(--text-dim)',
                               textTransform: 'uppercase', letterSpacing: '0.06em',
                               cursor: 'pointer' }}
                    >
                      {isOpen ? '▼' : '▶'} {g.name} ({g.emojis.length})
                    </button>
                    {/* Rendered only while open — all nine groups at once would
                        put ~1900 buttons in the DOM for a panel you mostly
                        interact with through the search box. */}
                    {isOpen && (
                      <EmojiRow label="" emojis={g.emojis.map((e) => toned(e, tone))}
                                onPick={insert} />
                    )}
                  </div>
                )
              })}
            </>
          )}
          <button
            style={{ width: '100%', marginTop: 6, fontSize: 11 }}
            onClick={() => fileRef.current?.click()}
          >
            🖼️ Upload PNG sticker…
          </button>
          <input
            ref={fileRef} type="file" accept="image/png,image/webp,image/gif" hidden
            onChange={async (e) => {
              const f = e.target.files?.[0]
              if (!f || !sid) return
              setUploadErr(null)
              try {
                await api.stickerUpload(sid, f, true, playhead)
                await refresh()
              } catch (err) {
                setUploadErr(err instanceof Error ? err.message : String(err))
              } finally {
                if (fileRef.current) fileRef.current.value = ''
              }
            }}
          />
          {uploadErr && (
            <div style={{ color: '#fbb', fontSize: 10, marginTop: 4 }}>{uploadErr}</div>
          )}
          <div style={{ fontSize: 10, color: 'var(--text-dim)', marginTop: 6 }}>
            Click an emoji or upload a PNG to drop at the playhead (3s).
          </div>
        </div>
      )}
    </div>
  )
}

/** One picker swatch: the ARTWORK the export will bake, never the OS glyph.
 *
 *  The panel used to render the raw character and let the browser paint it,
 *  which is the one rule the rest of this subsystem exists to enforce — and it
 *  is worst HERE, because a picker is a promise. On Windows you browsed Segoe
 *  UI Emoji, clicked, and got a Noto sticker; on a Mac you browsed Apple's.
 *  Same project, same click, three different designs, and the mismatch is
 *  visible in the *same frame* as the thing it disagrees with. Reported as
 *  "the preview is still the same as earlier" after the artwork switch — the
 *  stickers had changed, the grid you pick them from had not.
 *
 *  Falls back to the glyph only when the artwork genuinely 404s (an emoji no
 *  source covers), matching StickerLayer's posture: a wrong-font swatch beats
 *  an empty hole, but only as a last resort.
 *
 *  `loading="lazy"` is load-bearing now that the grid is the FULL set rather
 *  than 113 curated emoji. Every cache miss costs a CDN round trip inside
 *  `serve_emoji_png`, which is a SYNC endpoint on the shared anyio threadpool —
 *  the same pool every other request needs. The browser's ~6-connection cap
 *  keeps that from saturating, and fetching only what is actually scrolled into
 *  view is what makes opening a 400-emoji group cheap. After that they are
 *  immutably cached, so a group opens instantly the second time.
 */
function EmojiArt({ emoji, size, inline }: { emoji: string; size: number; inline?: boolean }) {
  const [failed, setFailed] = useState(false)
  if (failed) return <span style={{ fontSize: size }}>{emoji}</span>
  return (
    <img
      src={`/api/emoji/${codepointSeq(emoji)}.png`}
      alt={emoji}
      loading="lazy"
      draggable={false}
      onError={() => setFailed(true)}
      style={inline
        ? { width: size, height: size, display: 'inline-block',
            verticalAlign: '-0.15em', pointerEvents: 'none' }
        : { width: size, height: size, display: 'block', margin: '0 auto',
            pointerEvents: 'none' }}
    />
  )
}

function EmojiRow({ label, emojis, onPick }: { label: string; emojis: string[]; onPick: (e: string) => void }) {
  return (
    <div style={{ marginBottom: 8 }}>
      {label !== '' && (
        <div style={{ fontSize: 10, color: 'var(--text-dim)', textTransform: 'uppercase',
                      letterSpacing: 0.06 * 10 + 'em', marginBottom: 4 }}>{label}</div>
      )}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(8, 1fr)', gap: 2 }}>
        {emojis.map((e) => (
          <button
            key={e}
            onClick={() => onPick(e)}
            draggable
            onDragStart={(ev) => {
              ev.dataTransfer.effectAllowed = 'copy'
              ev.dataTransfer.setData('application/x-vai-emoji', e)
              ev.dataTransfer.setData('text/plain', e)
            }}
            title={`Click to insert at playhead, or drag onto the timeline`}
            style={{
              padding: '4px 0', fontSize: 18, background: 'var(--bg-2)',
              border: '1px solid var(--line)', borderRadius: 4, cursor: 'grab',
              lineHeight: 1, height: 28,
            }}
          >
            <EmojiArt emoji={e} size={20} />
          </button>
        ))}
      </div>
    </div>
  )
}
