"""Generate frontend/src/lib/pipTime.fixture.json (wave D3, lane E2): the
source frame the EXPORT shows in every output slot of a set of retimed PIP
clips — `frame_map.clip_frame_list`, the per-clip model the frame-map
goldens pin to decoded v1 renders (and test_b5_pip_frame_exact proves a PIP
render equals) — on real, probed bar-coded sources at 25 / 29.97 / 30.

lib/pipTime.test.ts reads it; tests/test_pip_time_fixture.py fails when the
checked-in file no longer matches the model.

    .venv/bin/python tests/gen_pip_time_fixture.py
"""
from __future__ import annotations

import json
import sys
import tempfile
from fractions import Fraction
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import frame_map_golden_lib as G  # noqa: E402

from video_ai_editor.edl import speed_presets as SP  # noqa: E402
from video_ai_editor.edl.schema import Clip  # noqa: E402
from video_ai_editor.render import frame_map as FM  # noqa: E402
from video_ai_editor.render.compositor import clip_frames  # noqa: E402

FIXTURE = Path(__file__).resolve().parents[1] / "frontend" / "src" / "lib" / "pipTime.fixture.json"
RATES = ("25", "30000/1001", "30")


def _kinds() -> list[tuple[str, dict]]:
    hero, montage = SP.resolve_speed(preset="hero"), SP.resolve_speed(preset="montage")
    return [("2x", {"speed": 2.0}), ("half", {"speed": 0.5}), ("1.5x", {"speed": 1.5}),
            ("hero", {"speed": hero}), ("montage", {"speed": montage}),
            ("rev", {"reverse": True}), ("rev1.5", {"reverse": True, "speed": 1.5}),
            ("rev-hero", {"reverse": True, "speed": hero}), ("freeze", {"freeze": 0.5})]


def build(work: Path) -> dict:
    srcs = {}
    for key, sid, rate in (("s30", 1, Fraction(30)), ("s25", 2, Fraction(25))):
        p = G.make_bar_source(work / f"{key}.mp4", G.SourceSpec(key=key, sid=sid, rate=rate, seconds=6.0))
        srcs[key] = G.probe_source(p)
    cases = []
    for fps_s in RATES:
        R = Fraction(fps_s)
        fps = G.fps_value(R)
        for key, info in srcs.items():
            for name, k in _kinds():
                c = Clip(src=key, start=0.0, speed=k.get("speed"), reverse=k.get("reverse", False))
                c.in_, c.out = 0.6, 2.6
                if "freeze" in k:
                    c.out = c.in_ + 1 / float(R)
                    c.freeze = k["freeze"]
                frames = FM.clip_frame_list(c, info, fps)[:clip_frames(c, fps)]
                clip = {k2: v for k2, v in json.loads(c.model_dump_json(by_alias=True)).items()
                        if k2 in ("in", "out", "start", "speed", "reverse", "freeze")}
                cases.append({"name": f"{name}@{fps_s}/{key}", "fps": fps,
                              "rate": [info.rate.numerator, info.rate.denominator],
                              "start_ticks": info.start_ticks,
                              "tb": [info.time_base.numerator, info.time_base.denominator],
                              "clip": clip, "frames": frames})
    return {"_": "generated by tests/gen_pip_time_fixture.py (frame_map.clip_frame_list on probed bar sources)",
            "cases": cases}


def dumps(d: dict) -> str:
    return json.dumps(d, separators=(",", ":")) + "\n"


if __name__ == "__main__":
    with tempfile.TemporaryDirectory() as tmp:
        FIXTURE.write_text(dumps(build(Path(tmp))))
    print(FIXTURE)
