"""The geometry goldens still describe the compositor (Wave D, spec §3.4).

``tests/goldens/geometry_cases.json`` pins where the export's ffmpeg chain puts
a clip's picture (fit/cover, rotate, crop-zoom/pan, keyframes, flip, opacity,
fades); ``frontend/src/lib/preview/render/geometry.test.ts`` holds the client
compositor to it. This side re-renders a representative subset through the
REAL compositor and requires the same measurements, so a compositor change
that moves a picture fails here until the goldens (and geometry.ts) follow.
"""
from __future__ import annotations

import shutil

import pytest

import geometry_golden_lib as lib

pytestmark = pytest.mark.skipif(shutil.which("ffmpeg") is None, reason="ffmpeg not on PATH")

#: One case per rule family (the full set is regenerated by gen_geometry_goldens).
LIVE = ("contain_portrait", "cover_pan_zoom", "rotate_20", "scale_073_pan", "kf_scale",
        "kf_start_offset", "vflip_rotate", "fades_speed2")

GOLD = {c["name"]: c for c in lib.load()["cases"]} if lib.GOLDEN.exists() else {}


def test_golden_covers_every_p1_geometry_feature():
    assert GOLD, "tests/goldens/geometry_cases.json missing: run tests/gen_geometry_goldens.py"
    names = " ".join(GOLD)
    for feature in ("contain", "cover", "cover_pan", "rotate", "scale", "pan", "kf_", "hflip", "vflip",
                    "opacity", "fade"):
        assert feature in names, feature
    assert {c.name for c in lib.cases()} == set(GOLD), "golden cases out of date with geometry_golden_lib"


@pytest.fixture(scope="module")
def sources(tmp_path_factory):
    return lib.ensure_sources(tmp_path_factory.mktemp("geo-src"))


@pytest.mark.parametrize("name", LIVE)
def test_live_render_matches_golden(name, sources, tmp_path):
    paths, infos = sources
    case = next(c for c in lib.cases() if c.name == name)
    measured = lib.render_case(case, paths, tmp_path)
    gold = GOLD[name]
    assert gold["sources"] == {k: infos[k].to_json() for k in gold["sources"]}
    for got, want in zip(measured, gold["frames"], strict=True):
        assert got["k"] == want["k"]
        if "gain" in want:
            assert got["gain"] == pytest.approx(want["gain"], abs=0.005), (name, got["k"])
            continue
        assert got["bbox"] == want["bbox"], (name, got["k"])
        for m, at in want["markers"].items():
            if at is None:
                assert got["markers"][m] is None, (name, got["k"], m)
            else:
                assert got["markers"][m] == pytest.approx(at, abs=0.25), (name, got["k"], m)


def test_keyframes_are_evaluated_at_clip_local_timeline_time():
    """Review RD2: the export evaluates a v1 clip's keyframes at the CLIP-LOCAL
    TIMELINE seconds of the displayed frame (the Properties panel's
    `clipLocalTime`), not at (source-local t − start). A clip at start = 1 s
    keyed x 0→300 over 2 s pans from its first frame (it used to show no pan
    for a whole second); geometry.ts evaluates the same time."""
    frames = {f["k"]: f for f in GOLD["kf_start_offset"]["frames"]}
    centre = [frames[k]["markers"]["white"][0] for k in (30, 45, 60, 75)]
    # local 0 s: x = 0, the picture centred
    assert centre[0] == pytest.approx(320, abs=0.5)
    # local 0.5 s: x = 75 → crop x 320 + 75 → 394 on the chroma grid, so the
    # picture sits 74 px left (before the fix this was local 1.5 s)
    assert centre[1] == pytest.approx(246, abs=0.5)
    assert centre[3] < centre[2] < centre[1]
    assert frames[89]["markers"]["white"] is None   # x ≈ 296 at 1.97 s: off the canvas


def test_keyframes_on_a_retimed_clip_follow_the_timeline_not_the_source():
    """A 2x clip keyed x 0→200 over 2 s: at timeline t into the clip the key
    time is t (x = 100·t), not the source's 2t (x = 200·t) — the picture
    moves left by x canvas px (kf_start_offset: x = 75 → 74 px on the
    chroma grid)."""
    two = {f["k"]: f for f in GOLD["kf_speed2"]["frames"]}
    for k in (0, 10, 20, 29):
        x = 100 * k / 30
        assert two[k]["markers"]["white"][0] == pytest.approx(320 - x, abs=2), k
