"""The geometry goldens still describe the compositor (Wave D, spec §3.4).

``tests/goldens/geometry_cases.json`` pins where the export's ffmpeg chain puts
a clip's picture (fit/cover, rotate, crop-zoom/pan, keyframes, flip, opacity,
fades); ``frontend/src/lib/preview/render/geometry.test.ts`` holds the client
compositor to it. This side re-renders a representative subset through the
REAL compositor and requires the same measurements, so a compositor change
that moves a picture fails here until the goldens (and geometry.ts) follow.
"""
from __future__ import annotations

import shutil

import pytest

import geometry_golden_lib as lib

pytestmark = pytest.mark.skipif(shutil.which("ffmpeg") is None, reason="ffmpeg not on PATH")

#: One case per rule family (the full set is regenerated by gen_geometry_goldens).
LIVE = ("contain_portrait", "cover_pan_zoom", "rotate_20", "scale_073_pan", "kf_scale",
        "kf_start_offset", "vflip_rotate", "fades_speed2",
        # Wave D3 (lane E1a): anamorphic sources and the keyframe clock
        "contain_pal43", "contain_hdv_portrait", "cover_pan_hdv", "kf_pan_pal169",
        "kf_speed_half", "kf_freeze", "kf_opacity_speed_half", "kf_shrink_about_centre",
        # review RD3: a static opacity keeps an odd pan on the chroma grid
        "scale_05_pan1_opacity",
        # wave E (F4a): Transform.flip_h / flip_v, mirrored before the turn
        "tflip_h_rotate", "tflip_h_cover_pan", "tflip_h_kf", "tflip_v_pal43",
        # wave E gate (X2): fades on a clip cut at in > 0 (the in-anchored
        # clock's negative pre-roll pts had them unfaded / black)
        "fades_in_offset", "fades_in_offgrid", "fades_in_offset_speed_half", "fades_in_offset_curve",
        "fades_in_offset_canvas_bg")

GOLD = {c["name"]: c for c in lib.load()["cases"]} if lib.GOLDEN.exists() else {}


def test_a_static_opacity_does_not_move_the_picture():
    """review RD3 (s27): scale 0.5 + pan (1, 1) at opacity 0.6 landed at
    [161, 91, 481, 271] against the opaque [162, 92, 482, 272]."""
    assert GOLD["scale_05_pan1_opacity"]["frames"][0]["bbox"] == GOLD["scale_05_pan1"]["frames"][0]["bbox"]


def test_golden_covers_every_p1_geometry_feature():
    assert GOLD, "tests/goldens/geometry_cases.json missing: run tests/gen_geometry_goldens.py"
    names = " ".join(GOLD)
    for feature in ("contain", "cover", "cover_pan", "rotate", "scale", "pan", "kf_", "hflip", "vflip",
                    "opacity", "fade", "pal43", "pal169", "hdv", "kf_freeze", "kf_curve", "kf_reverse", "tflip_"):
        assert feature in names, feature
    assert {c.name for c in lib.cases()} == set(GOLD), "golden cases out of date with geometry_golden_lib"


@pytest.fixture(scope="module")
def sources(tmp_path_factory):
    return lib.ensure_sources(tmp_path_factory.mktemp("geo-src"))


@pytest.mark.parametrize("name", LIVE)
def test_live_render_matches_golden(name, sources, tmp_path):
    paths, infos = sources
    case = next(c for c in lib.cases() if c.name == name)
    measured = lib.render_case(case, paths, tmp_path)
    gold = GOLD[name]
    assert gold["sources"] == {k: infos[k].to_json() for k in gold["sources"]}
    for got, want in zip(measured, gold["frames"], strict=True):
        assert got["k"] == want["k"]
        if "gain" in want:
            assert got["gain"] == pytest.approx(want["gain"], abs=0.005), (name, got["k"])
            continue
        assert got["bbox"] == want["bbox"], (name, got["k"])
        for m, at in want["markers"].items():
            if at is None:
                assert got["markers"][m] is None, (name, got["k"], m)
            else:
                assert got["markers"][m] == pytest.approx(at, abs=0.25), (name, got["k"], m)


def test_keyframes_are_evaluated_at_clip_local_timeline_time():
    """The export evaluates a v1 clip's keyframes at the CLIP-LOCAL TIMELINE
    seconds of the OUTPUT frame (`playhead - clip.start`, the UI's clock):
    a clip at start = 1 s keyed x 0→300 over 2 s pans from its first frame,
    and +x moves the picture RIGHT (a static pan's and the UI's meaning; the
    keyframed branch used to move it left)."""
    frames = {f["k"]: f for f in GOLD["kf_start_offset"]["frames"]}
    centre = [frames[k]["markers"]["white"][0] for k in (30, 45, 60, 75)]
    assert centre[0] == pytest.approx(320, abs=0.5)          # local 0 s: x = 0
    # local 0.5 s: x = 75 → crop 422 − 75 = 347 → 346 on the chroma grid
    assert centre[1] == pytest.approx(394, abs=0.5)
    assert centre[3] > centre[2] > centre[1]
    assert frames[89]["markers"]["white"] is None             # x ≈ 296 at 1.97 s: off the canvas


def test_keyframes_on_a_retimed_clip_follow_the_timeline_not_the_source():
    """A 2x clip keyed x 0→200 over 2 s: at timeline t into the clip x = 100·t
    (the source's clock would give 200·t)."""
    two = {f["k"]: f for f in GOLD["kf_speed2"]["frames"]}
    for k in (0, 10, 20, 29):
        x = 100 * k / 30
        assert two[k]["markers"]["white"][0] == pytest.approx(320 + x, abs=2), k


def test_a_slow_clip_animates_every_output_frame():
    """0.5x repeats each source frame; the keyframe still advances on every
    OUTPUT frame (it used to hold the source frame's value for two)."""
    half = {f["k"]: f["markers"]["white"][0] for f in GOLD["kf_speed_half"]["frames"]}
    assert half[0] < half[1] < half[2] < half[3]
    for k, cx in half.items():
        x = 200 * (k / 30) / 2
        assert cx == pytest.approx(320 + x, abs=2), k
    gains = {f["k"]: f["gain"] for f in GOLD["kf_opacity_speed_half"]["frames"]}
    assert gains[0] > gains[1] > gains[2] > gains[3]


def test_a_keyed_zoom_is_about_the_centre_and_can_shrink():
    """scale keyed 0.5 → 1.5 with y = 20: the white centre marker stays at
    (320, 200) the whole way (a crop-zoom anchored where the first frame put
    `iw` drifted), and at 0.5 the picture is a centred half-size box."""
    fr = {f["k"]: f for f in GOLD["kf_shrink_about_centre"]["frames"]}
    for k in fr:
        # ±1 px: a picture of even width w can only be centred on the chroma
        # grid when (640 − w)/2 is even (the static branch shares the rule)
        assert fr[k]["markers"]["white"] == pytest.approx([320, 200], abs=1.05), k
    assert fr[0]["bbox"] == [160, 110, 480, 290]


def test_anamorphic_sources_fit_their_displayed_shape():
    """720x576 SAR 16:15 displays 768x576 (4:3): contained in 640x360 it is
    480x360 at x = 80 (the stored 5:4 shape gave 450 px at x = 94); HDV
    1440x1080 SAR 4:3 is 16:9 (360x202.5 in a 360x640 canvas)."""
    assert GOLD["contain_pal43"]["frames"][0]["bbox"] == [80, 0, 560, 360]
    assert GOLD["contain_pal43"]["sources"]["pal43"]["w"] == 768
    assert GOLD["contain_hdv_portrait"]["frames"][0]["bbox"] == [0, 218, 360, 420]
    assert GOLD["contain_pal169_portrait"]["frames"][0]["bbox"] == [0, 218, 360, 420]
