// GENERATED by tests/gen_voice_fx_goldens.py from edl/voice_effects.py —
// do not edit (tests/test_voice_effects.py pins it equal to the table).
export const VOICE_FX_TABLE = {
  "presets": [
    {
      "id": "chipmunk",
      "label": "Chipmunk",
      "hint": "High and squeaky: up 9 semitones",
      "icon": "voiceChipmunk",
      "aliases": [
        "helium",
        "squeaky",
        "high pitched",
        "high-pitched",
        "cartoon"
      ],
      "stages": [
        {
          "kind": "pitch",
          "params": {
            "semitones": 9.0
          },
          "scale": {
            "semitones": 0.0
          }
        }
      ]
    },
    {
      "id": "deep",
      "label": "Deep",
      "hint": "A lower, fuller voice: down 4 semitones",
      "icon": "voiceDeep",
      "aliases": [
        "low",
        "lower",
        "baritone",
        "bass voice",
        "deeper"
      ],
      "stages": [
        {
          "kind": "pitch",
          "params": {
            "semitones": -4.0
          },
          "scale": {
            "semitones": 0.0
          }
        }
      ]
    },
    {
      "id": "monster",
      "label": "Monster",
      "hint": "Growling and huge: down 8 semitones with grit",
      "icon": "voiceMonster",
      "aliases": [
        "demon",
        "beast",
        "villain",
        "ogre",
        "evil"
      ],
      "stages": [
        {
          "kind": "pitch",
          "params": {
            "semitones": -8.0
          },
          "scale": {
            "semitones": 0.0
          }
        },
        {
          "kind": "drive",
          "params": {
            "k": 2.5
          },
          "scale": {
            "k": 0.0
          }
        },
        {
          "kind": "biquad",
          "params": {
            "type": "lowpass",
            "f": 3500.0,
            "q": 0.707,
            "mix": 1.0,
            "passes": 1
          },
          "scale": {
            "mix": 0.0
          }
        },
        {
          "kind": "gain",
          "params": {
            "db": -1.5
          },
          "scale": {
            "db": 0.0
          }
        }
      ]
    },
    {
      "id": "robot",
      "label": "Robot",
      "hint": "Metallic and buzzing, like a machine",
      "icon": "voiceRobot",
      "aliases": [
        "robotic",
        "android",
        "cyborg",
        "machine",
        "dalek",
        "droid"
      ],
      "stages": [
        {
          "kind": "echo",
          "params": {
            "in_gain": 1.0,
            "out_gain": 0.6,
            "delays_ms": [
              7.0,
              14.0,
              21.0
            ],
            "decays": [
              0.7,
              0.5,
              0.35
            ]
          },
          "scale": {
            "decays": 0.0,
            "out_gain": 1.0
          }
        },
        {
          "kind": "ring",
          "params": {
            "freq": 45.0,
            "depth": 1.0
          },
          "scale": {
            "depth": 0.0
          }
        }
      ]
    },
    {
      "id": "echo",
      "label": "Echo",
      "hint": "Repeats every quarter second and dies away",
      "icon": "voiceEcho",
      "aliases": [
        "echoes",
        "echoey",
        "delay",
        "canyon"
      ],
      "stages": [
        {
          "kind": "echo",
          "params": {
            "in_gain": 1.0,
            "out_gain": 0.85,
            "delays_ms": [
              250.0,
              500.0,
              750.0
            ],
            "decays": [
              0.5,
              0.25,
              0.125
            ]
          },
          "scale": {
            "decays": 0.0,
            "out_gain": 1.0
          }
        }
      ]
    },
    {
      "id": "reverb",
      "label": "Hall",
      "hint": "A big hall: two seconds of reverb",
      "icon": "voiceHall",
      "aliases": [
        "hall",
        "reverb",
        "reverberation",
        "cathedral",
        "church",
        "big room",
        "concert hall",
        "roomy"
      ],
      "stages": [
        {
          "kind": "reverb",
          "params": {
            "dry": 0.85,
            "tail": 0.0125,
            "rt60": 1.8,
            "predelay_ms": 25.0
          },
          "scale": {
            "tail": 0.0,
            "dry": 1.0
          }
        }
      ]
    },
    {
      "id": "telephone",
      "label": "Telephone",
      "hint": "Thin and band-limited, like a phone call",
      "icon": "voicePhone",
      "aliases": [
        "phone",
        "phone call",
        "cell phone",
        "landline"
      ],
      "stages": [
        {
          "kind": "biquad",
          "params": {
            "type": "highpass",
            "f": 400.0,
            "q": 0.707,
            "mix": 1.0,
            "passes": 2
          },
          "scale": {
            "mix": 0.0
          }
        },
        {
          "kind": "biquad",
          "params": {
            "type": "lowpass",
            "f": 3000.0,
            "q": 0.707,
            "mix": 1.0,
            "passes": 2
          },
          "scale": {
            "mix": 0.0
          }
        },
        {
          "kind": "gain",
          "params": {
            "db": 3.0
          },
          "scale": {
            "db": 0.0
          }
        }
      ]
    },
    {
      "id": "megaphone",
      "label": "Megaphone",
      "hint": "Loud, honky and distorted",
      "icon": "voiceMegaphone",
      "aliases": [
        "bullhorn",
        "loudspeaker",
        "loud hailer",
        "loudhailer",
        "pa system"
      ],
      "stages": [
        {
          "kind": "biquad",
          "params": {
            "type": "highpass",
            "f": 500.0,
            "q": 0.707,
            "mix": 1.0,
            "passes": 2
          },
          "scale": {
            "mix": 0.0
          }
        },
        {
          "kind": "biquad",
          "params": {
            "type": "lowpass",
            "f": 4000.0,
            "q": 0.707,
            "mix": 1.0,
            "passes": 1
          },
          "scale": {
            "mix": 0.0
          }
        },
        {
          "kind": "biquad",
          "params": {
            "type": "peaking",
            "f": 2000.0,
            "q": 1.0,
            "mix": 1.0,
            "passes": 1,
            "gain_db": 6.0
          },
          "scale": {
            "mix": 0.0
          }
        },
        {
          "kind": "drive",
          "params": {
            "k": 3.0
          },
          "scale": {
            "k": 0.0
          }
        },
        {
          "kind": "gain",
          "params": {
            "db": -2.0
          },
          "scale": {
            "db": 0.0
          }
        }
      ]
    },
    {
      "id": "radio",
      "label": "Radio",
      "hint": "An old AM radio broadcast",
      "icon": "voiceRadio",
      "aliases": [
        "am radio",
        "walkie talkie",
        "walkie-talkie",
        "old radio",
        "vintage radio",
        "broadcast"
      ],
      "stages": [
        {
          "kind": "biquad",
          "params": {
            "type": "highpass",
            "f": 300.0,
            "q": 0.707,
            "mix": 1.0,
            "passes": 1
          },
          "scale": {
            "mix": 0.0
          }
        },
        {
          "kind": "biquad",
          "params": {
            "type": "lowpass",
            "f": 3500.0,
            "q": 0.707,
            "mix": 1.0,
            "passes": 2
          },
          "scale": {
            "mix": 0.0
          }
        },
        {
          "kind": "biquad",
          "params": {
            "type": "peaking",
            "f": 1200.0,
            "q": 0.8,
            "mix": 1.0,
            "passes": 1,
            "gain_db": 4.0
          },
          "scale": {
            "mix": 0.0
          }
        },
        {
          "kind": "drive",
          "params": {
            "k": 1.5
          },
          "scale": {
            "k": 0.0
          }
        },
        {
          "kind": "gain",
          "params": {
            "db": 1.0
          },
          "scale": {
            "db": 0.0
          }
        }
      ]
    },
    {
      "id": "underwater",
      "label": "Underwater",
      "hint": "Muffled and wobbling, as if under water",
      "icon": "voiceUnderwater",
      "aliases": [
        "under water",
        "muffled",
        "submerged",
        "drowning",
        "muffle"
      ],
      "stages": [
        {
          "kind": "biquad",
          "params": {
            "type": "lowpass",
            "f": 450.0,
            "q": 0.707,
            "mix": 1.0,
            "passes": 2
          },
          "scale": {
            "mix": 0.0
          }
        },
        {
          "kind": "vibrato",
          "params": {
            "f": 2.0,
            "d": 0.6
          },
          "scale": {
            "d": 0.0
          }
        },
        {
          "kind": "gain",
          "params": {
            "db": 4.0
          },
          "scale": {
            "db": 0.0
          }
        }
      ]
    },
    {
      "id": "vibrato",
      "label": "Vibrato",
      "hint": "A wavering, singing pitch",
      "icon": "voiceVibrato",
      "aliases": [
        "wobble",
        "warble",
        "wavering",
        "shaky voice",
        "trembling",
        "tremble"
      ],
      "stages": [
        {
          "kind": "vibrato",
          "params": {
            "f": 6.0,
            "d": 0.5
          },
          "scale": {
            "d": 0.0
          }
        }
      ]
    }
  ],
  "intensity_range": [
    0.0,
    1.0
  ],
  "default_intensity": 1.0,
  "pitch_eps_semitones": 0.01,
  "reverb_ir_seconds": 2.0,
  "sample_rate": 48000
} as const
