// lib/pipTime: the source instant a retimed PIP shows, pinned against the
// PYTHON model of the export (`frame_map.clip_frame_list` on probed bar-coded
// sources — the model the frame-map goldens pin to decoded v1 renders, and
// the one test_b5_pip_frame_exact proves a PIP render equals). The fixture
// is generated by tests/gen_pip_time_fixture.py (run it with .venv/bin/python;
// tests/test_pip_time_fixture.py keeps it current); each case lists the
// source frame of every output slot.
//
// A <video> seeked to `frameTime` shows the latest source frame whose pts is
// at or before it, so that frame must be the model's frame for the slot.

import { describe, expect, it } from 'vitest'
import fixture from './pipTime.fixture.json'
import { pipIsRetimed, pipTiming } from './pipTime'
import { timeOf } from './preview/timeline/timebase'
import type { EdlClip } from './preview/timeline/framePlan'

interface Case {
  name: string
  fps: number
  rate: [number, number]
  start_ticks: number
  tb: [number, number]
  clip: EdlClip
  frames: number[]
}

const cases = (fixture as unknown as { cases: Case[] }).cases

/** The frame a <video> displays at `t`: the last one with pts <= t. */
function shownFrame(c: Case, t: number): number {
  const start = (c.start_ticks * c.tb[0]) / c.tb[1]
  return Math.floor(((t - start) * c.rate[0]) / c.rate[1] + 1e-9)
}

describe('pipTiming: the export frame of every output slot', () => {
  it.each(cases.map((c) => [c.name, c] as const))('%s', (_name, c) => {
    const clip = { ...c.clip, id: 'p', src: 's' } as EdlClip
    const got = c.frames.map((_f, j) => shownFrame(c, pipTiming(clip, timeOf(j, c.fps), c.fps).frameTime))
    expect(got).toEqual(c.frames)
  })

  it('discriminates: the 1x map would show other frames', () => {
    const c = cases.find((x) => x.name === '2x@30/s30')!
    const one = c.frames.map((_f, j) => shownFrame(c, (c.clip.in ?? 0) + timeOf(j, c.fps) + 0.001))
    expect(one).not.toEqual(c.frames)
  })
})

describe('pipTiming: playback rates and continuity', () => {
  const base = { id: 'p', src: 's', in: 1, out: 5, start: 0 } as EdlClip
  it('a constant speed plays forwards at that speed', () => {
    const tm = pipTiming({ ...base, speed: 2 }, 0.5, 30)
    expect(tm).toMatchObject({ kind: 'forward', rate: 2 })
    expect(tm.time).toBeCloseTo(2, 9)
  })
  it('a curve plays at its instantaneous speed and its integral', () => {
    const c = { ...base, speed: { curve: [[0, 1], [0.5, 0.25], [1, 1]] } } as EdlClip
    expect(pipTiming(c, 0, 30).rate).toBeCloseTo(1, 9)
    const mid = pipTiming(c, 3.2, 30)     // footprint 4 / 0.625 = 6.4 s; 3.2 s is the curve's valley
    expect(mid.rate).toBeCloseTo(0.25, 6)
    expect(mid.time).toBeCloseTo(3, 6)    // half the source (the curve is symmetric)
  })
  it('a reverse runs backwards from the range end', () => {
    const tm = pipTiming({ ...base, reverse: true }, 1, 30)
    expect(tm.kind).toBe('reverse')
    expect(tm.rate).toBe(-1)
    expect(tm.time).toBeCloseTo(4, 9)
  })
  it('a freeze holds one instant with no rate', () => {
    const c = { ...base, out: 1 + 1 / 30, freeze: 2 } as EdlClip
    const a = pipTiming(c, 0, 30)
    const b = pipTiming(c, 1.9, 30)
    expect(a).toEqual(b)
    expect(a).toMatchObject({ kind: 'freeze', rate: 0 })
  })
  it('only a retimed PIP leaves the 1x path', () => {
    expect(pipIsRetimed(base)).toBe(false)
    expect(pipIsRetimed({ ...base, speed: 1 })).toBe(false)
    expect(pipIsRetimed({ ...base, speed: 1.5 })).toBe(true)
    expect(pipIsRetimed({ ...base, reverse: true })).toBe(true)
    expect(pipIsRetimed({ ...base, freeze: 1 })).toBe(true)
    expect(pipIsRetimed({ ...base, speed: { curve: [[0, 1], [1, 2]] } })).toBe(true)
  })
})
